[build]
  command = "hugo --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.139.0"

[context.production.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/themes"
  to = "/themes/"
  status = 301

[[redirects]]
  from = "/articles"
  to = "/articles/"
  status = 301
